name: Validate project quality

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: "Install dependencies"
      run: |
          python -m pip install PyGithub
    - name: Install dataiku keys
      env:
        DATAIKU_READONLY_DEPLOY_KEY: ${{ secrets.dataiku_readonly_deploy_key }}
      run: |
        mkdir ~/dep_keys
        echo "$DATAIKU_READONLY_DEPLOY_KEY" > ~/dep_keys/dataiku_rsa
        chmod 600 ~/dep_keys/dataiku_rsa
        ls -l ~/dep_keys/dataiku_rsa
    - name: Inspect secret 2
      env:
        DATAIKU_READONLY_DEPLOY_KEY2: ${{ secrets.dataiku_readonly_deploy_key2 }}
      run: |
        echo "$DATAIKU_READONLY_DEPLOY_KEY2"
    - name: Inspect secret
      run: |
        head -c30 ~/dep_keys/dataiku_rsa
    - name: Inspect 2
      run: head -c30 ~/dep_keys/dataiku_rsa
    - name: Inspect 3
      env:
        DATAIKU_READONLY_DEPLOY_KEY: ${{ secrets.dataiku_readonly_deploy_key }}
      run: echo "$DATAIKU_READONLY_DEPLOY_KEY"
    - name: Inspect 4
      env:
        DATAIKU_READONLY_DEPLOY_KEY: ${{ secrets.dataiku_readonly_deploy_key }}
      run: echo "${DATAIKU_READONLY_DEPLOY_KEY:0:15}"
    - name: Inspect 5
      run: |
        echo "static string echo"
    - name: Inspect 6
      run: |
        foovar='foob'
        echo "var $foovar"
    - name: Inspect 7
      run: |
        filecont=`more ~/dep_keys/dataiku_rsa`
        echo "filecont $filecont"
    - name: Install dataiku repo
      run: |
        mkdir ~/dataiku
        ssh-agent bash -c 'ssh-add ~/dep_keys/dataiku_rsa ; git clone --single-branch --branch master git@github.com:TeliaSoneraNorge/dataiku.git ~/dataiku'
    - name: Validate PQ body
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_BODY: ${{ github.event.pull_request.body }}
      run: |
        python ~/dataiku/gitutil/validate-pr-quality.py "$GITHUB_TOKEN" "$PR_BODY"
